[versions]
agp = "8.12.2"
android-material = "1.12.0"
android-shell = "1.0.0"
android-volley = "1.2.1"
androidx-activity = "1.10.1"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-junit = "1.3.0"
androidx-localbroadcast = "1.1.0"
androidx-preference = "1.2.1"
androidx-rules = "1.7.0"
androidx-runner = "1.7.0"
androidx-work = "2.10.3"
guardian-jtorctl = "0.4.5.7"
junit-jupiter = "5.13.4"
navigation-fragment-ktx = "2.9.3"
orchestrator = "1.6.1"
retrofit = "3.0.0"
rootbeer = "0.1.1"
tor-android = "0.4.8.17.2"
pcap-core = "1.8.2"
pcap-factory = "1.8.2"
kotlin = "2.2.10"
coroutines = "1.10.2"
serialization = "1.9.0"
app-icon-name-changer = "1.0.7"
androidx-biometric = "1.1.0"
androidx-lifecycle = "2.9.3"
screengrab = "2.1.1"
upnp = "1.0.0"

[libraries]
android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }
android-shell = { group = "com.jaredrummler", name = "android-shell", version.ref = "android-shell" }
android-volley = { group = "com.android.volley", name = "volley", version.ref = "android-volley" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-localbroadcast = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "androidx-localbroadcast" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-fragment-ktx" }
androidx-orchestrator = { module = "androidx.test:orchestrator", version.ref = "orchestrator" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-rules" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-runner" }
androidx-work = { group = "androidx.work", name = "work-runtime", version.ref = "androidx-work" }
androidx-work-kotlin = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }
guardian-jtorctl = { group = "info.guardianproject", name = "jtorctl", version.ref = "guardian-jtorctl" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
retrofit-lib = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
rootbeer-lib = { module = "com.scottyab:rootbeer-lib", version.ref = "rootbeer" }
tor-android = { group = "info.guardianproject", name = "tor-android", version.ref = "tor-android" }
pcap-core = { group = "org.pcap4j", name = "pcap4j-core", version.ref = "pcap-core" }
pcap-factory = { group = "org.pcap4j", name = "pcap4j-packetfactory-static", version.ref = "pcap-factory" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
appiconnamechanger = { group = "com.github.myinnos", name = "AppIconNameChanger", version.ref = "app-icon-name-changer" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "androidx-biometric" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "androidx-lifecycle" }
screengrab = { group = "tools.fastlane", name = "screengrab", version.ref = "screengrab" }
upnp = { group = "com.netzarchitekten", name = "upnp", version.ref = "upnp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
